package ROSML.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_EInterfaces extends EnumerationDescriptorBase {

  public EnumerationDescriptor_EInterfaces() {
    super(0xf7db56d1b41e4c13L, 0x9756a014feb108beL, 0x18dbf75c7f56da76L, "EInterfaces", "r:d670596f-f26c-43d2-8e17-a7b3e68888bf(ROSML.structure)/1791297253455354486");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_msg_0 = new EnumerationDescriptor.MemberDescriptor("msg", "msg", 0x18dbf75c7f56da77L, "r:d670596f-f26c-43d2-8e17-a7b3e68888bf(ROSML.structure)/1791297253455354487");
  private final EnumerationDescriptor.MemberDescriptor myMember_srv_0 = new EnumerationDescriptor.MemberDescriptor("srv", "srv", 0x18dbf75c7f56da78L, "r:d670596f-f26c-43d2-8e17-a7b3e68888bf(ROSML.structure)/1791297253455354488");
  private final EnumerationDescriptor.MemberDescriptor myMember_action_0 = new EnumerationDescriptor.MemberDescriptor("action", "action", 0x18dbf75c7f56da7bL, "r:d670596f-f26c-43d2-8e17-a7b3e68888bf(ROSML.structure)/1791297253455354491");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xf7db56d1b41e4c13L, 0x9756a014feb108beL, 0x18dbf75c7f56da76L, 0x18dbf75c7f56da77L, 0x18dbf75c7f56da78L, 0x18dbf75c7f56da7bL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList0(myIndex, myMember_msg_0, myMember_srv_0, myMember_action_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "msg":
        return myMember_msg_0;
      case "srv":
        return myMember_srv_0;
      case "action":
        return myMember_action_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
