package ROSML.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Acciones = 0;
  public static final int Conexion = 1;
  public static final int ConexionPuerto = 2;
  public static final int IElementoRed = 3;
  public static final int INodo = 4;
  public static final int IPuerto = 5;
  public static final int Mensaje = 6;
  public static final int Nodo = 7;
  public static final int Proyecto = 8;
  public static final int Servicio = 9;
  public static final int Servidor = 10;
  public static final int Topico = 11;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xf7db56d1b41e4c13L, 0x9756a014feb108beL);
    builder.put(0x5f9f55b2215f05faL, Acciones);
    builder.put(0x5d8e854cb6b9f03L, Conexion);
    builder.put(0x52ae22b433653219L, ConexionPuerto);
    builder.put(0x45d1f7827d3faed1L, IElementoRed);
    builder.put(0x6e04103ea7fd6c7aL, INodo);
    builder.put(0x52ae22b4336975deL, IPuerto);
    builder.put(0x2126fce3999aa945L, Mensaje);
    builder.put(0x5d8e854cb6b6efbL, Nodo);
    builder.put(0x5d8e854cb6b6ef9L, Proyecto);
    builder.put(0x5f9f55b2215b96f8L, Servicio);
    builder.put(0x2126fce3999aabd2L, Servidor);
    builder.put(0x5d8e854cb6b6f01L, Topico);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
